FROM node:13.12.0 as build

WORKDIR /app

ENV PATH /app/node-modules/.bin:$PATH

COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@9.1.12

COPY . /app

RUN ng build --prod --output-path=dist

FROM nginx:1.19.3-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
# When the container starts replace the env.js with the valies from environment variables
# CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
# CMD ["nginx","-g","daemon off;"]

