FROM node:13.12.0 as build

WORKDIR /app

ENV PATH /app/node-modules/.bin:$PATH

COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@.10.1.7

COPY . /app

RUN ng build --prod --output-path=dist

FROM nginx:1.19.3-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]

